version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: voice-agent-frontend-prod
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - voice-agent-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voice-agent-backend-prod
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SPEECH_PROVIDER=${SPEECH_PROVIDER:-sarvam_ai}
      - SARVAM_API_KEY=${SARVAM_API_KEY}
      - SARVAM_API_URL=${SARVAM_API_URL:-https://api.sarvam.ai/v1}
      - SUPRSEND_API_KEY=${SUPRSEND_API_KEY}
      - GUPSHUP_API_KEY=${GUPSHUP_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - API_KEY=${API_KEY}
      - ENVIRONMENT=production
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - voice-agent-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo:6.0
    container_name: voice-agent-mongo-prod
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=voice_agent
    networks:
      - voice-agent-network
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/voice_agent --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  voice-agent-network:
    driver: bridge

volumes:
  mongo_data:
